### ISSUE TITLE
Control.loop does not actually play in a loop.

### ISSUE THREAD

**Issue by chanindev** [KevinVan720/styled_widget#3]
In the video, it starts over again with each loop. Please see the attached video for reference. 

How to solved this.

Thank you.

https://github.com/KevinVan720/animated_styled_widget/assets/3127520/bd9dd24c-73f3-4280-9ef1-0f90013f1ba3

**Comment by chanindev** [comment]
Solved. use version 0.3.5.

**Comment by vance-liu** [comment]
The latest version also has this issue.
